all:HW04

HW04:
	g++ -std=c++0x -c ALP_EMİR_BİLEK_161044049_HW04.cpp
	g++ -std=c++0x -c Course.cpp
	g++ -std=c++0x -c Classroom.cpp
	g++ -std=c++0x -c Student.cpp
	g++ -std=c++0x -c Lecturer.cpp
	g++ -std=c++0x -c Admin.cpp

	g++ -o HW04 ALP_EMİR_BİLEK_161044049_HW04.o Course.o Classroom.o Lecturer.o Admin.o Student.o

	./HW04


clean:
	rm *.o HW04	
