all:HW05

HW05:
	g++ -std=c++0x -c main.cpp
	g++ -std=c++0x -c Employee.cpp
	g++ -std=c++0x -c UNI.cpp
	g++ -std=c++0x -c Secretary.cpp
	g++ -std=c++0x -c Lecturer.cpp
	g++ -std=c++0x -c Officer.cpp
	g++ -std=c++0x -c ResearchAssistant.cpp
	g++ -std=c++0x -c YOK.cpp
	g++ -o HW06 main.o Employee.o YOK.o UNI.o Secretary.o Lecturer.o Officer.o ResearchAssistant.o	

	./HW06


clean:
	rm	*.o HW06